name: finsentinel
version: '1.0.0'
config-version: 2

profile: finsentinel

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  finsentinel:
    staging:
      +materialized: view
      +schema: staging
    gold:
      +materialized: table
      +schema: gold
